services:
  redis_cluster_bootstrap:
    build:
      context: .
      dockerfile: ./dockerfiles/bootstrap.Dockerfile
    image: redis_cluster_bootstrap_7_nodes:latest
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
      - redis_node_5
      - redis_node_6
      - redis_replica_node_0_0
      - redis_replica_node_0_1
      - redis_replica_node_1_0
      - redis_replica_node_1_1
      - redis_replica_node_2_0
      - redis_replica_node_2_1
      - redis_replica_node_3_0
      - redis_replica_node_3_1
      - redis_replica_node_4_0
      - redis_replica_node_4_1
      - redis_replica_node_5_0
      - redis_replica_node_5_1
      - redis_replica_node_6_0
      - redis_replica_node_6_1
    environment:
      - REDIS_NODE_0_PORT=7000
      - REDIS_NODE_1_PORT=7001
      - REDIS_NODE_2_PORT=7002
      - REDIS_NODE_3_PORT=7003
      - REDIS_NODE_4_PORT=7004
      - REDIS_NODE_5_PORT=7005
      - REDIS_NODE_6_PORT=7006
      - REDIS_REPLICA_NODE_0_0_PORT=7007
      - REDIS_REPLICA_NODE_0_1_PORT=7008
      - REDIS_REPLICA_NODE_1_0_PORT=7009
      - REDIS_REPLICA_NODE_1_1_PORT=7010
      - REDIS_REPLICA_NODE_2_0_PORT=7011
      - REDIS_REPLICA_NODE_2_1_PORT=7012
      - REDIS_REPLICA_NODE_3_0_PORT=7013
      - REDIS_REPLICA_NODE_3_1_PORT=7014
      - REDIS_REPLICA_NODE_4_0_PORT=7015
      - REDIS_REPLICA_NODE_4_1_PORT=7016
      - REDIS_REPLICA_NODE_5_0_PORT=7017
      - REDIS_REPLICA_NODE_5_1_PORT=7018
      - REDIS_REPLICA_NODE_6_0_PORT=7019
      - REDIS_REPLICA_NODE_6_1_PORT=7020
    volumes:
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_0:
    build:
      context: .
      dockerfile: ../dockerfiles/node.Dockerfile
    image: redis_node:latest
    environment:
        - REDIS_PORT=7000
        - REDIS_COM_PORT=17000
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7001
        - REDIS_COM_PORT=17001
    depends_on:
      - redis_node_0
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_2:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7002
        - REDIS_COM_PORT=17002
    depends_on:
      - redis_node_0
      - redis_node_1
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_3:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7003
        - REDIS_COM_PORT=17003
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_4:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7004
        - REDIS_COM_PORT=17004
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_5:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7005
        - REDIS_COM_PORT=17005
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_6:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7006
        - REDIS_COM_PORT=17006
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
      - redis_node_5
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_0_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7007
        - REDIS_COM_PORT=17007
    depends_on:
      - redis_node_0
    ports:
      - "7007:7007"
      - "17007:17007"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_0_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7008
        - REDIS_COM_PORT=17008
    depends_on:
      - redis_node_0
    ports:
      - "7008:7008"
      - "17008:17008"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_1_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7009
        - REDIS_COM_PORT=17009
    depends_on:
      - redis_node_1
    ports:
      - "7009:7009"
      - "17009:17009"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_1_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7010
        - REDIS_COM_PORT=17010
    depends_on:
      - redis_node_1
    ports:
      - "7010:7010"
      - "17010:17010"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_2_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7011
        - REDIS_COM_PORT=17011
    depends_on:
      - redis_node_2
    ports:
      - "7011:7011"
      - "17011:17011"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_2_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7012
        - REDIS_COM_PORT=17012
    depends_on:
      - redis_node_2
    ports:
      - "7012:7012"
      - "17012:17012"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_3_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7013
        - REDIS_COM_PORT=17013
    depends_on:
      - redis_node_3
    ports:
      - "7013:7013"
      - "17013:17013"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_3_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7014
        - REDIS_COM_PORT=17014
    depends_on:
      - redis_node_3
    ports:
      - "7014:7014"
      - "17014:17014"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_4_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7015
        - REDIS_COM_PORT=17015
    depends_on:
      - redis_node_4
    ports:
      - "7015:7015"
      - "17015:17015"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_4_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7016
        - REDIS_COM_PORT=17016
    depends_on:
      - redis_node_4
    ports:
      - "7016:7016"
      - "17016:17016"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_5_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7017
        - REDIS_COM_PORT=17017
    depends_on:
      - redis_node_5
    ports:
      - "7017:7017"
      - "17017:17017"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_5_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7018
        - REDIS_COM_PORT=17018
    depends_on:
      - redis_node_5
    ports:
      - "7018:7018"
      - "17018:17018"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_6_0:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7019
        - REDIS_COM_PORT=17019
    depends_on:
      - redis_node_6
    ports:
      - "7019:7019"
      - "17019:17019"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_replica_node_6_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7020
        - REDIS_COM_PORT=17020
    depends_on:
      - redis_node_6
    ports:
      - "7020:7020"
      - "17020:17020"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network

networks:
  node_cluster_network:
    driver: bridge
