services:
  redis_cluster_bootstrap:
    build:
      context: .
      dockerfile: ./dockerfiles/bootstrap.Dockerfile
    image: redis_cluster_bootstrap_7_nodes:latest
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
      - redis_node_5
      - redis_node_6
    environment:
      - REDIS_NODE_0_PORT=7000
      - REDIS_NODE_1_PORT=7001
      - REDIS_NODE_2_PORT=7002
      - REDIS_NODE_3_PORT=7003
      - REDIS_NODE_4_PORT=7004
      - REDIS_NODE_5_PORT=7005
      - REDIS_NODE_6_PORT=7006
    volumes:
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_0:
    build:
      context: .
      dockerfile: ../dockerfiles/node.Dockerfile
    image: redis_node:latest
    environment:
        - REDIS_PORT=7000
        - REDIS_COM_PORT=17000
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7001
        - REDIS_COM_PORT=17001
    depends_on:
      - redis_node_0
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_2:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7002
        - REDIS_COM_PORT=17002
    depends_on:
      - redis_node_0
      - redis_node_1
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_3:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7003
        - REDIS_COM_PORT=17003
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_4:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7004
        - REDIS_COM_PORT=17004
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_5:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7005
        - REDIS_COM_PORT=17005
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_6:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7006
        - REDIS_COM_PORT=17006
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
      - redis_node_3
      - redis_node_4
      - redis_node_5
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network


networks:
  node_cluster_network:
    driver: bridge
