services:
  redis_node_0:
    build:
      context: .
      dockerfile: dockerfiles/node.Dockerfile
    image: redis_node:latest
    environment:
        - REDIS_PORT=7000
        - REDIS_COM_PORT=17000
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_1:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7001
        - REDIS_COM_PORT=17001
    depends_on:
      - redis_node_0
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_node_2:
    image: redis_node:latest
    environment:
        - REDIS_PORT=7002
        - REDIS_COM_PORT=17002
    depends_on:
      - redis_node_0
      - redis_node_1
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - node_cluster_network
  redis_cluster_bootstrap:
    build:
      context: .
      dockerfile: dockerfiles/bootstrap.Dockerfile
    image: redis_cluster_bootstrap:latest
    depends_on:
      - redis_node_0
      - redis_node_1
      - redis_node_2
    environment:
      - REDIS_NODE_0_PORT=7000
      - REDIS_NODE_1_PORT=7001
      - REDIS_NODE_2_PORT=7002
    volumes:
      - ./scripts:/scripts
    networks:
      - node_cluster_network

networks:
  node_cluster_network:
    driver: bridge
